server {
    listen 80;
    server_name fptest.yemel.org;

    root /srv/fptest/www;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/calculate {
        include uwsgi_params;
        uwsgi_pass unix:/srv/fptest/uwsgi.sock;
    }
}
